### ISSUE TITLE
Blog posts

### ISSUE THREAD

**Issue by petedavisdev** [petedavisdev/vuepress-theme-base#6]
```
- label: "Post"
    name: "post"
    folder: "_posts"
    create: true
    fields:
      - label: "Title"
        name: "title"
        widget: "string"

      - label: "Publish Date"
        name: "date"
        widget: "date"

      - label: "Featured Image"
        name: "image"
        widget: "image"

      - label: "Summary"
        name: "summary"
        widget: "text"
```

- [x] PostList
- [x] PostListItem
